### ISSUE TITLE
Too many noise in the flowviz

### ISSUE THREAD

**Issue by fherran** [HanLingsgjk/CSCV#3]
Dear Team,

I'd like to thank you for releasing ur code for the paper "ScaleFlow++".

I've tested it on my data, but there is too many noise in the flowviz make it unable to detect the moving objects.

See the picture below.

The red bounding box is just the objects, and the text in black is just the mean pixels of the bbox.

![image](https://github.com/user-attachments/assets/e5fc712f-a128-410f-b986-c46d05c3f13f)

**Comment by HanLingsgjk** [comment]
Hello, can you provide me with your test images? So that I can identify the problem

**Comment by fherran** [comment]
It's a drone footage frame data, I'm suppose this happens due to the nature of the drone movement, am I correct?

**Comment by HanLingsgjk** [comment]
If it is a drone, two issues need to be considered: one is whether the photo is blurry, and the other is whether the lighting is sufficient. We have tested the clear drone perspective photos and the effect is still acceptable.

**Comment by fherran** [comment]
Yes the drone footage taken on the daylight, but I don't think this considered a problem.

Could you please give me any tip regarding pre processing the frames

**Comment by HanLingsgjk** [comment]
If you could provide me with your test images, I might be able to offer more accurate advice

**Comment by HanLingsgjk** [comment]
Some of the drone images I tested myself were fine

**Comment by HanLingsgjk** [comment]
![image](https://github.com/user-attachments/assets/9447a4ca-b904-498f-a627-9bb85e95ad3b)

**Comment by HanLingsgjk** [comment]
This is an example of remote sensing perspective motion perception that we tested ourselves

**Comment by ElseFaisal** [comment]
![Uploading sec8_frame_000090.png…]()
Here is the example of my data

**Comment by ElseFaisal** [comment]
![Uploading sec8_frame_000090.png…]()

**Comment by fherran** [comment]
![Uploading sec8_frame_000090.png…]()

**Comment by HanLingsgjk** [comment]
Your image seems to have failed to upload. After dragging the image into the box, you need to wait for ‘...’ to disappear before clicking send

**Comment by fherran** [comment]
![test29](https://github.com/user-attachments/assets/20d310a8-8d9b-4fed-8030-1028564ab3d5)

**Comment by fherran** [comment]
Also Mr.Han, I think the mistake due to the input frames as BGR not RGB, is it correct?

**Comment by HanLingsgjk** [comment]
I think this clear image should not cause optical flow failure. Can you also upload the second image? I'll test it out

**Comment by fherran** [comment]
![frame1](https://github.com/user-attachments/assets/fcd3c7e5-7dca-4538-ace0-6d094618767a)
![frame2](https://github.com/user-attachments/assets/5039e2a2-9718-4000-978e-2a8dfde1ffa8)

Here are the two consecutive frames for ur reference.
 
Note: These not the same as the picture I uploaded earlier.

Thanks for ur support.

**Comment by fherran** [comment]
In addition, I resized the frames to 864 * 864 due to CUDA out of memory issues.

**Comment by HanLingsgjk** [comment]
<img width="250" alt="0f4431d86d3eef3cb9a7c721da0c517" src="https://github.com/user-attachments/assets/9c03a870-d059-41cf-b1f0-554e675d5495">

**Comment by HanLingsgjk** [comment]
<img width="250" alt="774813a3613ab835fa4a7b33b70d91f" src="https://github.com/user-attachments/assets/95d34bce-0de2-4711-8495-ae6415316d93">

**Comment by HanLingsgjk** [comment]
<img width="250" alt="37b93291fd483333c72610b641107ac" src="https://github.com/user-attachments/assets/de93fd85-d15b-41b0-833d-d4b07d016193">

**Comment by HanLingsgjk** [comment]
These three images are the first image, the second image, and the optical flow result. I cropped them

**Comment by HanLingsgjk** [comment]
I'm not sure if there's a problem with the weights you're using

**Comment by fherran** [comment]
Could you please specify the weights file name you've used?

**Comment by HanLingsgjk** [comment]
https://drive.google.com/drive/folders/129lbJWkcMwxispcRVXOvUGF12GuHbhX3?usp=drive_link  Demo_Scaleflowpp.pth

By the way, smaller motion amplitudes may indeed affect the network's estimation results (as this is rarely the case in the scenario I trained). I suggest you try not shrinking but predicting the large image through cropping （I noticed that the motion amplitude in your example is very small, and scaling will further reduce the pixel motion amplitude）.

**Comment by fherran** [comment]
Yes the same weights I've used. I'll try and let you know.

**Comment by fherran** [comment]
![image](https://github.com/user-attachments/assets/b53d2be4-5cee-4054-a6b1-634d70cf123b)

I tried to crop the manually and the same result appeared, why? Should I change the weights? Or if you can provide me with the weights file you've been used.

Many thanks.

**Comment by fherran** [comment]
I noticed that the model perform good on one frame and the next frame performs poorly and so on, ... why?

See the images below for ur reference.

![image](https://github.com/user-attachments/assets/8ffaa9ae-21dc-49d8-82ab-bd36b0804e80)

![image](https://github.com/user-attachments/assets/5dccba35-0b35-45ae-a3c4-ca80b7549d1d)

The first image is the first frame, and the second is the next frame.

**Comment by fherran** [comment]
Hi Mr.Han,

I'd like to say that the mistake was in the frames (there was duplication) and not in the model nor the weights.

Thanks for your patience on answering all my questions.

Faisal.

**Comment by HanLingsgjk** [comment]
I hope you enjoy using it, don’t forget to give a star. I will appreciate it.
